COMPILER = g++
SRC = ejercicio16.cpp
FLAGS = -std=c++14 -o
BIN = ejercicio16
PARAMS = 1010


all:	build	run clean

build:
	$(COMPILER) $(SRC) $(FLAGS) $(BIN)
run:
	./$(BIN) $(PARAMS)
clean:
	rm $(BIN)
