COMPILER = g++
SRC = ejercicio15.cpp
FLAGS = -std=c++14 -o
BIN = ejercicio15
PARAMS = 1010


all:	build	run clean

build:
	$(COMPILER) $(SRC) $(FLAGS) $(BIN)
run:
	./$(BIN) $(PARAMS)
clean:
	rm $(BIN)
