COMPILER = g++
SRC = ejercicio10.cpp
FLAGS = -std=c++14 -o
BIN = ejercicio10
PARAMS = 1.1 -2 1


all:	build	run clean

build:
	$(COMPILER) $(SRC) $(FLAGS) $(BIN)
run:
	./$(BIN) $(PARAMS)
clean:
	rm $(BIN)
